export const BASE_URL = 'http://localhost:5001'
export const Desktop_URL = `${BASE_URL}/desktop`
export const User_URL = `${BASE_URL}/user`
export const Auth_URL = `${BASE_URL}/auth`
export const Login_URL = `${BASE_URL}/auth/login`
export const Register_URL = `${BASE_URL}/auth/register`
export const Logout_URL = `${BASE_URL}/auth/logout`
// export const Refresh_URL = `${BASE_URL}/auth/refresh`
export const Laptop_URL = `${BASE_URL}/laptop`
